export const GET_SAVED_TWEETS_REQUEST = 'GET_SAVED_TWEETS_REQUEST'
export const GET_SAVED_TWEETS_SUCCESS = 'GET_SAVED_TWEETS_SUCCESS'
export const GET_SAVED_TWEETS_FAILED = 'GET_SAVED_TWEETS_FAILED'

export const GET_LIKED_TWEETS_REQUEST = 'GET_LIKED_TWEETS_REQUEST'
export const GET_LIKED_TWEETS_SUCCESS = 'GET_LIKED_TWEETS_SUCCESS'
export const GET_LIKED_TWEETS_FAILED = 'GET_LIKED_TWEETS_FAILED'
