export const GET_TOP_TWEETS_REQUEST = 'GET_TOP_TWEETS_REQUEST'
export const GET_TOP_TWEETS_SUCCESS = 'GET_TOP_TWEETS_SUCCESS'
export const GET_TOP_TWEETS_FAILED = 'GET_TOP_TWEETS_FAILED'

export const GET_LATEST_TWEETS_REQUEST = 'GET_LATEST_TWEETS_REQUEST'
export const GET_LATEST_TWEETS_SUCCESS = 'GET_LATEST_TWEETS_SUCCESS'
export const GET_LATEST_TWEETS_FAILED = 'GET_LATEST_TWEETS_FAILED'

export const GET_POPULAR_USER_REQUEST = 'GET_POPULAR_USER_REQUEST'
export const GET_POPULAR_USER_SUCCESS = 'GET_POPULAR_USER_SUCCESS'
export const GET_POPULAR_USER_FAILED = 'GET_POPULAR_USER_FAILED'