export const GET_ALL_TWEETS_REQUEST = 'GET_ALL_TWEETS_REQUEST'
export const GET_ALL_TWEETS_SUCCESS = 'GET_ALL_TWEETS_SUCCESS'
export const GET_ALL_TWEETS_FAILED = 'GET_ALL_TWEETS_FAILED'

export const GET_ALL_REPLIES_REQUEST = 'GET_ALL_REPLIES_REQUEST'
export const GET_ALL_REPLIES_SUCCESS = 'GET_ALL_REPLIES_SUCCESS'
export const GET_ALL_REPLIES_FAILED = 'GET_ALL_REPLIES_FAILED'

export const ADD_LIKES_REQUEST = 'ADD_LIKES_REQUEST'
export const ADD_LIKES_SUCCESS = 'ADD_LIKES_SUCCESS'
export const ADD_LIKES_FAILED = 'ADD_LIKES_FAILED'

export const UNLIKE_REQUEST = 'UNLIKE_REQUEST'
export const UNLIKE_SUCCESS = 'UNLIKE_SUCCESS'
export const UNLIKE_FAILED = 'UNLIKE_FAILED'

export const ADD_SAVE_REQUEST = 'ADD_SAVE_REQUEST'
export const ADD_SAVE_SUCCESS = 'ADD_SAVE_SUCCESS'
export const ADD_SAVE_FAILED = 'ADD_SAVE_FAILED'

export const UNSAVE_REQUEST = 'UNSAVE_REQUEST'
export const UNSAVE_SUCCESS = 'UNSAVE_SUCCESS'
export const UNSAVE_FAILED = 'UNSAVE_FAILED'

export const GET_ONE_USER_REQUEST = 'GET_ONE_USER_REQUEST'
export const GET_ONE_USER_SUCCESS = 'GET_ONE_USER_SUCCESS'
export const GET_ONE_USER_FAILED = 'GET_ONE_USER_FAILED'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'