export const GET_OWN_TWEETS_REQUEST = 'GET_OWN_TWEETS_REQUEST'
export const GET_OWN_TWEETS_SUCCESS = 'GET_OWN_TWEETS_SUCCESS'
export const GET_OWN_TWEETS_FAILED = 'GET_OWN_TWEETS_FAILED'

export const GET_ALL_FOLLOWERS_REQUEST = 'GET_ALL_FOLLOWERS_REQUEST'
export const GET_ALL_FOLLOWERS_SUCCESS = 'GET_ALL_FOLLOWERS_SUCCESS'
export const GET_ALL_FOLLOWERS_FAILED = 'GET_ALL_FOLLOWERS_FAILED'

export const GET_ALL_FOLLOWING_REQUEST = 'GET_ALL_FOLLOWING_REQUEST'
export const GET_ALL_FOLLOWING_SUCCESS = 'GET_ALL_FOLLOWING_SUCCESS'
export const GET_ALL_FOLLOWING_FAILED = 'GET_ALL_FOLLOWING_FAILED'