export const GET_ALL_FOLLOWERS_REQUEST = 'GET_ALL_FOLLOWERS_REQUEST'
export const GET_ALL_FOLLOWERS_SUCCESS = 'GET_ALL_FOLLOWERS_SUCCESS'
export const GET_ALL_FOLLOWERS_FAILED = 'GET_ALL_FOLLOWERS_FAILED'